name: "wmt_lven_default"

data:
    src: "lv"
    trg: "en"
    train: "test/data/lv-en/train.tok.bpe"
    dev: "test/data/lv-en/dev.tok.bpe"
    test: "test/data/lv-en/test.tok.bpe"
    level: "bpe"
    lowercase: False
    max_sent_length: 50
    src_voc_min_freq: 0
    src_voc_limit: 100000
    trg_voc_min_freq: 0
    trg_voc_limit: 100000

testing:
    beam_size: 5
    alpha: 1.0

training:
    random_seed: 42
    optimizer: "adam"
    learning_rate: 0.0002
    learning_rate_min: 0.0000005
    weight_decay: 0.0
    clip_grad_norm: 1.0
    batch_size: 80
    scheduling: "plateau"
    patience: 8
    decrease_factor: 0.7
    early_stopping_metric: "ppl"
    epochs: 20
    validation_freq: 2000
    logging_freq: 1000
    eval_metric: "bleu"
    model_dir: "models/wmt_lven_default"
    overwrite: False
    shuffle: True
    use_cuda: True
    max_output_length: 100
    print_valid_sents: [0, 1, 2]

model:
    encoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 500
            scale: False
        hidden_size: 500
        bidirectional: True
        dropout: 0.3
        num_layers: 1
    decoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 500
            scale: False
        emb_scale: False
        hidden_size: 1000
        dropout: 0.3
        hidden_dropout: 0.3
        num_layers: 1
        input_feeding: True
        init_hidden: "bridge"
        attention: "bahdanau"
